version: 0.0
os: linux
files:
  - source: /coit-frontend
    destination: /home/ubuntu/
    overwrite: true
permissions:
  - object: /home/ubuntu/
    pattern: "**"
    owner: root
    group: root
    mode: 755
hooks:
  AfterInstall:
    - location: coit-frontend/script/installationscript.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: coit-frontend/script/startserver.sh
      timeout: 300
      runas: root
